### ISSUE TITLE
use with alternate backends

### ISSUE THREAD

**Issue by joprice** [nwolverson/purescript-language-server#104]
When using purescript-native with purescript-language-server, I get errors like the following for foreign imports:

```
[PureScript MissingFFIImplementations] [E]   The following values are not
   10  defined in the foreign module for module Main:
run
```

At first, I worked around this by providing a js file exporting an empty function, but eventually I found the `codegenTargets` setting and configured that to only use `corefn`. I was surprised I had to do this, since I would expect the command run by the editor to be the same as what's run by spago build. This would avoid accidental rebuilds and allows for one source of truth for the configuration. But, perhaps that's unavoidable? I don't know if this language server calls purs directly, and how the `backend` setting in spago.dhall should propagate. Maybe having a note in the readme would be helpful for people using other backends.

**Comment by nwolverson** [comment]
The language server wraps `purs ide server`, which provides fast rebuild functionality, and much more. It also allows you to run a "full" build with e.g. `spago` as required, but this is not related. The language server does not particularly tie itself to `spago`, and even when configured to be used as a build command, as the source of dependency globs etc, it is not involved in the rebuild process.

"One source of truth for configuration" is something that might have existed if purescript had some kind of project configuration, spago may become this but for now the compiler knows nothing of such configuration and here we are more "not assuming". I don't really want to get into a situation of having a "if codegen targets are set use them, else consult spago, else use a default" (and `spago` would probably need to be able to answer a "what is the backend" query or some such).

This project doesn't really have documentation over the settings, historically due to the fact that they are pointed at the vscode extension for docs (but mostly because I am lazy and writing docs is hard), certainly don't object to adding a note on this there - it should also be noted under the docs for alternate backends, just as `--codegen corefn` is/was.

**Comment by nwolverson** [comment]
Updated docs to mention alternative backends.
