### ISSUE TITLE
Commands not registered?

### ISSUE THREAD

**Issue by andys8** [nwolverson/purescript-language-server#105]
I wanted to give `organi{s,z}eImports` a try. I didn't figure out how to execute a command with `Vim/Coc`. It might be possible and just me not knowing how to do it.

What I noticed is that `CocList commands` does list language server commands, but not for purescript:

![image](https://user-images.githubusercontent.com/13085980/94936154-2aa28480-04ce-11eb-81d6-7fec3cf110ac.png)

I'm not sure if something is off with the registration of commands or I'm misunderstanding something here.

## Followup

Followup (which should probably be a new issue): Let's assume executing `purescript.organiseImports` is working fine - would it make sense to alias it as `editor.action.organizeImport`? I think that's how the action is called in TS, go, python and other servers and docs refer to this binding which would be the same across language servers.

https://github.com/neoclide/coc.nvim/blob/99188750671907ab091e68eebc90ec906088a51d/src/handler/index.ts#L290

**Comment by andys8** [comment]
I'm also wondering if the "command list" feature is something specific to `CoC` and not language servers in general. E.g. this one lists commands in the `package.json`, but is also meant for CoC only.

https://github.com/iamcco/coc-spell-checker/blob/bc9802c667aac992fab2f47b0da096c28dca0dfd/package.json

**Comment by nwolverson** [comment]
The purescript language server gives a response of some provided commands, it doesn't include everything, but you should see some commands via `capabilities.executeCommandProvider`. `package.json` is not a LSP concept - it happens that this language server runs on node but you can check the specification: https://microsoft.github.io/language-server-protocol/specification. For vscode the commands shown in the menu are actually defined in the vscode extension wrapping the language server - I can't speak for any other context.

I'm not aware of any standardised commands, if you have a reference to such a standard I would be interested - otherwise I think it is correct that this server uses a consistent prefix.

`organiseImports` currently requires a command parameter specifying the filename in question - as far as I can see, this isn't a thing in the protocol, that we have the "current" filename for a command available automatically - so probably requires some effort to call the command directly

**Comment by nwolverson** [comment]
The code you linked appears to be related to some kind of organise import code action, i.e. it's a client-side command which triggers some code actions
