### ISSUE TITLE
Foregins format and TS compiled sources

### ISSUE THREAD

**Issue by wclr** [nwolverson/purescript-language-server#157]
So there are two small proposals:

1) Use default prettier formatting for all foreign sources (TS and JS).

2) Remove TS compiled JS sources from git? This one is discussible of course, JS compilations of TS sources are needed if there is some workflow assume installing language-server as purs package or some other direct downloads from the repo.

**Comment by nwolverson** [comment]
I don't care about formatting, no problem with applying a formatter there (excluding generated JS I guess).

This repo is used as a dependency of vscode-ide-purescript, the actual dependency won't involve any of those foreign imports but of course that would still block the build. I think there was a suggestion (by you?) to just write the imports in JS directly with the facilities now to typecheck JS, I'm sure I avoided that in the past due to annoyances with typescript import interop

**Comment by wclr** [comment]
> This repo is used as a dependency of vscode-ide-purescript, 

Ah, as soon as this is the case these JS versions are needed, I forgot about it.

> I think there was a suggestion (by you?) 

Probably by me, but now I think that in LS's case, it is easier to work with typed TS interfaces than to mess with JSDoc stuff to get proper typing and autocompletion to reduce possible mistakes.

**Comment by nwolverson** [comment]
Resolved in #159 I believe
