### ISSUE TITLE
Usage with generic plugins

### ISSUE THREAD

**Issue by dakom** [nwolverson/purescript-language-server#38]
I tried integrating this project with Vim plugins that communicate over generic Language Servers, but I haven't gotten it to work yet. Any insight you have is appreciated:

LanguageClient-neovim Issue: https://github.com/autozimu/LanguageClient-neovim/issues/527

Ale PR: https://github.com/w0rp/ale/pull/1737

(btw - is there a way to generate some log on the server side? I see the client can trigger it but maybe there's some independent flag?)

Thanks!

**Comment by nwolverson** [comment]
Logging is currently all via the `window/logMessage` LS message, there hasn't been a need to do that server side so far; but I'm sure we could log to a file also.

The linked logs on that issue do seem to show the `logMessage` though, maybe there's nowhere to display that?

**Comment by nwolverson** [comment]
Per slack discussion I'm happy to help work through this, looking at your logs I suspect no config has been received so the server is not started (because otherwise if the config arrives after starting the server, it won't be configured right... and in vscode at least the config is sent 1st thing).

Can you try running with args `--stdio --config {}` - it looks like I never managed to bring in a arg parser so literally in that order!

**Comment by dakom** [comment]
oooh, I snuck that into ALE to test real quick - getting some errors (better than nothing!)

"failed to fill whole buffer"

And then it's honing in on the module imports and saying it can't find them

**Comment by nwolverson** [comment]
Can't find imports usually indicates that the project wasn't build at startup time (externs with the correct version are not present in `output/` when `purs ide server` loads dependencies), so that's a correct user-level error if you see it (there's a `window/showMessage` to prompt the user to build)

**Comment by dakom** [comment]
d'oh forgot about that... so now I'm getting a "server already running needs to restart" error, BUT after ignoring that and doing some purposefully wrong errors - it's working in ALE!!!

**Comment by dakom** [comment]
LanguageServer is still not working however - will post an update there and continue another time. Thanks!

**Comment by dakom** [comment]
Thanks! Haven't been writing Purescript lately unfortunately, but good to know :)

**Comment by tssm** [comment]
In that case @nwolverson I think it is OK to close the issue. The only problem I see is that it doesn't find external modules but I guess it is because I am using psc-package instead of Bower

**Comment by sriharshachilakapati** [comment]
I think it is safe to close the issue now. I was using the same setup daily with no issues now. Found some others, but now it's all resolved.

I use NVIM 0.3.4 with LanguageClient_neovim version 0.1.142 and purescript-language-server 0.12.7.

My configuration can be found here: https://github.com/sriharshachilakapati/dotfiles/blob/master/.vimrc#L78-L315
